---
- name: Update Ubuntu Servers - Starting deploy
  hosts: all
  become: true
  tasks:
    - name: Ubuntu Like | Update System
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
...
